apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: app-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: app1.xyz.com
      http:
        paths:
          - backend:
              serviceName: app-service
              servicePort: 5555    
    