apiVersion: v1
kind: Service
metadata:
  name: app-service 
spec:
  selector:
    app: app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  externalTrafficPolicy: Cluster
  type: LoadBalancer